server:
  port: 8089
  
spring:
  jpa:
    properties:
      show_sql: true
      use_sql_comments: true
      format_sql: true
    hibernate:
      ddl-auto: create
#  datasource:
#    driver-class-name: org.h2.Driver
#    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
#    username: sa
#    password: sa

logging:
    level:
      org.springframework.web: DEBUG
      guru.springframework.controllers: DEBUG
      org.hibernate: DEBUG

kingfisher:
  createAdminContentOnEmpty: true